using Insight.Training;

namespace Insight.Tests;

public class YoloTrainingEngineTests
{
    [Fact]
    public void BuildLaunchPlanReadsGeneratedYoloCommand()
    {
        var workDir = CreateTempDirectory();
        try
        {
            File.WriteAllText(
                Path.Combine(workDir, "训练命令.txt"),
                """
                # Generated by Insight
                yolo detect train model=yolov8s.pt data="C:/dataset/data.yaml" epochs=12 batch=4 imgsz=640 device=0
                """);

            var engine = new YoloTrainingEngine();
            var plan = engine.BuildLaunchPlan(new TrainingRequest
            {
                PythonPath = "python",
                WorkDir = workDir,
                Params = new TrainingParams()
            });

            Assert.Equal("python", plan.PythonPath);
            Assert.Equal(workDir, plan.WorkingDirectory);
            Assert.Contains("from ultralytics.cfg import entrypoint", plan.Arguments);
            Assert.Contains("detect train", plan.Arguments);
            Assert.Contains("yolov8s.pt", plan.Arguments);
        }
        finally
        {
            DeleteTempDirectory(workDir);
        }
    }

    [Fact]
    public void TryParseMetricsParsesTrainingAndValidationLines()
    {
        var engine = new YoloTrainingEngine();

        var train = engine.TryParseMetrics("1/100 2.75G 1.026 1.266 1.18 14 640");
        var validation = engine.TryParseMetrics("all 20 20 0.91 0.82 0.76 0.55");

        Assert.NotNull(train);
        Assert.Equal("1/100", train.Epoch);
        Assert.Equal(1.026, train.BoxLoss);
        Assert.Equal(1.0, train.Progress);

        Assert.NotNull(validation);
        Assert.Equal("val", validation.Epoch);
        Assert.Equal(0.76, validation.Map50);
        Assert.Equal(0.55, validation.Map5095);
    }

    [Fact]
    public void FindBestArtifactReturnsNewestCompletedRun()
    {
        var workDir = CreateTempDirectory();
        try
        {
            var older = Path.Combine(workDir, "runs", "detect", "train", "weights");
            var newer = Path.Combine(workDir, "runs", "detect", "train2", "weights");
            Directory.CreateDirectory(older);
            Directory.CreateDirectory(newer);

            var olderPt = Path.Combine(older, "best.pt");
            var newerPt = Path.Combine(newer, "best.pt");
            File.WriteAllText(olderPt, "older");
            File.WriteAllText(newerPt, "newer");
            Directory.SetLastWriteTime(Path.GetDirectoryName(older)!, DateTime.Now.AddMinutes(-3));
            Directory.SetLastWriteTime(Path.GetDirectoryName(newer)!, DateTime.Now);

            var engine = new YoloTrainingEngine();
            var best = engine.FindBestArtifact(workDir, DateTime.Now.AddMinutes(-5));

            Assert.Equal(newerPt, best);
        }
        finally
        {
            DeleteTempDirectory(workDir);
        }
    }

    private static string CreateTempDirectory()
    {
        var path = Path.Combine(Path.GetTempPath(), "InsightTests_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }

    private static void DeleteTempDirectory(string path)
    {
        if (Directory.Exists(path))
        {
            Directory.Delete(path, recursive: true);
        }
    }
}
